version: '3'

services:
   web:
      build: .
      image: ${DOCKER_IMAGE_NAME}
      env_file:
        - "./.env.db"
      environment:
         DEBUG: 'pulldasher*'
         MOCK_AUTH_AS_USER: "fakeuser"
      ports:
         - ${APP_PORT}:8090         # Map the container's port 8080 to the host's APP_PORT
                                    # NOTE: The host port will need to match
                                    # the callback URL specified in the GitHub
                                    # application setting.
         - ${DEBUG_PORT}:9229       # Map debugging port to localhost:DEBUG_PORT
      volumes:
         - .:/opt/pulldasher        # Mount the current directory to /opt/pulldasher
      entrypoint: 'node --inspect=127.0.0.1:9229 bin/pulldasher'
   db:
      image: "mariadb:latest"
      env_file: "./.env.db"
      volumes:
         - data-volume:/var/lib/mysql   # Create a persistent volume so that we don't lose data between restarts
      expose:
        - 3306
      ports:
         - ${DB_PORT}:3306
volumes:
   data-volume:

