version: '2'

services:
   web:
      build: .
      entrypoint: '/opt/pulldasher/entrypoint.sh'
      environment:
         DEBUG: pulldasher*         # Enables all debug prints and opens 127.0.0.1:9229 for remote debugging
         MOCK_AUTH_AS_USER: "fakeuser"
      ports:
         - 3000:3000                # Map the container's port 8080 to the host's 8080
                                    # NOTE: The host port will need to match
                                    # the callback URL specified in the GitHub
                                    # application setting.

         - 9229:9229                # Map debugging port to localhost
      volumes:
         - .:/opt/pulldasher        # Mount the current directory to /opt/pulldasher
   db:
      image: "mysql:latest"
      command: --authentication_policy=mysql_native_password
      volumes:
         - ./db_data:/var/lib/mysql   # Create a persistent volume so that we don't lose data between restarts
      environment:
         # Please use strong passwords if you are deploying pulldasher in a
         # production environment.
         MYSQL_ROOT_PASSWORD: pulldasher
         MYSQL_DATABASE: pulldasher
         MYSQL_USER: pulldasher
         MYSQL_PASSWORD: pulldasher
volumes:
   db_data:
