#!/bin/bash

: "${SCHEMA_FILE:?SCHEMA_FILE must be defined and non-empty}"

docker-compose exec db \
   sh -c 'mysqldump --databases ${MYSQL_DATABASE} --no-data --skip-add-drop-table --skip-dump-date -u${MYSQL_USER} -p${MYSQL_PASSWORD}' \
   > $SCHEMA_FILE

sed -i -e "s/CREATE TABLE/CREATE TABLE IF NOT EXISTS/" $SCHEMA_FILE

