ALTER TABLE `comments`
ADD COLUMN `repo` VARCHAR(255) NULL FIRST;
--
ALTER TABLE `commit_statuses`
ADD COLUMN `repo` VARCHAR(255) NULL FIRST;
--
ALTER TABLE `issues`
ADD COLUMN `repo` VARCHAR(255) NULL FIRST;
--
ALTER TABLE `pull_labels`
ADD COLUMN `repo` VARCHAR(255) NULL FIRST;
--
ALTER TABLE `pull_signatures`
ADD COLUMN `repo` VARCHAR(255) NULL FIRST;
--
ALTER TABLE `pulls`
ADD COLUMN `repo` VARCHAR(255) NULL FIRST;
